/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.io.PrintWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author brendan
 */
public class questionBuilder extends javax.swing.JFrame {

    /**
     * Creates new form questionBuilder
     */
    String file;
    public questionBuilder(String fileName) {
        initComponents();
        file = fileName;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        submitQuestion = new javax.swing.JButton();
        submitQuestionBank = new javax.swing.JButton();
        tf_question = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_optionA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_optionB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_optionC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_optionD = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_correctAnswer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_feedback = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        submitQuestion.setText("Next Question");
        submitQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQuestionActionPerformed(evt);
            }
        });

        submitQuestionBank.setText("Done");
        submitQuestionBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitQuestionBankActionPerformed(evt);
            }
        });

        tf_question.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_question.setToolTipText("Enter your question here.");
        tf_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_questionActionPerformed(evt);
            }
        });

        jLabel1.setText("Question:");

        tf_optionA.setToolTipText("Enter an answer for the question:");

        jLabel2.setText("Option A)");

        jLabel3.setText("Option B)");

        jLabel4.setText("Option C)");

        jLabel5.setText("Option D)");

        tf_correctAnswer.setToolTipText("This must have exactly the same text as one of your four answers.");

        jLabel6.setText("Correct Answer)");

        tf_feedback.setToolTipText("This will appear after answering the question.");
        tf_feedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_feedbackActionPerformed(evt);
            }
        });

        jLabel7.setText("Feedback)");

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(submitQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(submitQuestionBank, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1)
                                .addComponent(tf_question)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tf_correctAnswer, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tf_optionB, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                                                .addComponent(tf_optionA))
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)))
                                    .addGap(229, 229, 229)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4)
                                            .addComponent(tf_optionC)
                                            .addComponent(tf_optionD, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))
                                .addComponent(tf_feedback))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_question, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_optionC, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(tf_optionA))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_optionD, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(tf_optionB))
                .addGap(52, 52, 52)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_correctAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_feedback, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitQuestionBank, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQuestionActionPerformed
            String question = tf_question.getText();
            String optionA = tf_optionA.getText();
            String optionB = tf_optionB.getText();
            String optionC = tf_optionC.getText();
            String optionD = tf_optionD.getText();
            String correctAnswer = tf_correctAnswer.getText();
            String feedback = tf_feedback.getText();
            
            try {
                FileWriter fw = new FileWriter(file, true);
                PrintWriter pw = new PrintWriter(fw);
		fw.write(question + "," + optionA + "," + optionB + "," + optionC + "," + optionD + "," + correctAnswer + "," + feedback);
                fw.close();
            }
            
            
	    catch (IOException e) {
	    e.printStackTrace();
            }
    }//GEN-LAST:event_submitQuestionActionPerformed

    private void tf_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_questionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_questionActionPerformed

    private void tf_feedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_feedbackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_feedbackActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        File CSVfile = new File(file);
        CSVfile.delete();
 
        
        engagementTeam et = new engagementTeam();
        et.setLocationRelativeTo(null);
        et.show(); 
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void submitQuestionBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitQuestionBankActionPerformed
        
        
        engagementTeam et = new engagementTeam();
        et.setLocationRelativeTo(null);
        et.show(); 
        this.dispose();
    }//GEN-LAST:event_submitQuestionBankActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(questionBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(questionBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(questionBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(questionBuilder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String file = "";
                new questionBuilder(file).setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton submitQuestion;
    private javax.swing.JButton submitQuestionBank;
    private javax.swing.JTextField tf_correctAnswer;
    private javax.swing.JTextField tf_feedback;
    private javax.swing.JTextField tf_optionA;
    private javax.swing.JTextField tf_optionB;
    private javax.swing.JTextField tf_optionC;
    private javax.swing.JTextField tf_optionD;
    private javax.swing.JTextField tf_question;
    // End of variables declaration//GEN-END:variables
}
